name: Bug report
description: Report a bug in Fluent Launcher
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Only one bug should be reported in this issue. If you have multiple issues, please file another bug report and reference the related issues.**
        **If you are unsure whether the behavior you have seen is expected, or have any questions, please go to discussions and ask for help.**

  - type: textarea
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please describe what you expected to happen.
      
  - type: textarea
    attributes:
      label: Environment
      description: Please describe your system environment if applicable.
      placeholder: |
        Windows version: 
        Fluent Launcher version: 

  - type: textarea
    attributes:
      label: Attachment
      description: Please upload screentshots, log and any related files.
