name: Build

on: workflow_dispatch

jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, arm64]
    env:
      Solution_Name: Natsurainko.FluentLauncher
      Project_Directory: Natsurainko.FluentLauncher
      Configuration: Release
      Packages_DirectoryName: AppPackages
      Packages_Directory: Natsurainko.FluentLauncher\AppPackages
    name: Build (${{ matrix.architecture }})

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Configure NuGet Source
      run: dotnet nuget add source "https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json"

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create app package
      run: |
        msbuild $env:Solution_Name /p:Platform=$env:Platform /p:AppxBundlePlatforms="$env:Appx_Bundle_Platforms" /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:AppxPackageDir="$env:Appx_Package_Dir" /p:GenerateAppxPackageOnBuild=true
      env:
        Appx_Bundle: Never
        Platform: ${{ matrix.architecture }}
        Appx_Bundle_Platforms: ${{ matrix.architecture }}
        Appx_Package_Build_Mode: SideloadOnly
        Appx_Package_Dir: ${{ env.Packages_DirectoryName }}\ # DO NOT REMOVE THE TRAILING SLASH
    
    - name: Create .msixupload
      id: create_msixupload
      run: |
        $msixFile = Get-Item -Path "${{ env.Packages_Directory }}\*\*.msix"
        $packageName = [System.IO.Path]::GetFileNameWithoutExtension($msixFile.FullName)
        echo "::set-output name=packageName::$packageName"

        $sourcePath = "${{ env.Packages_Directory }}\*\*.msix*"
        Compress-Archive -Path $sourcePath -DestinationPath "$packageName.zip"
        mv "$packageName.zip" "$packageName.msixupload"

    - name: Upload .msixupload to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: .msixupload
        path: ${{ steps.create_msixupload.outputs.packageName }}.msixupload

    - name: Upload .msix to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: .msix
        path: ${{ env.Packages_Directory }}\*\${{ steps.create_msixupload.outputs.packageName }}.msix

        
  release:
    name: Release
    needs: build
    runs-on: windows-latest
    env:
      SigningKey_Path: SigningKey.pfx

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: .msix
        path: ./artifacts

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.PFX_BASE64_ENCODED }}")
        [IO.File]::WriteAllBytes("${{ env.SigningKey_Path }}", $pfx_cert_byte)

    # Upload the MSIX package as an artifact
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: MSIX Package
    #     path: ${{ env.Packages_Directory }}/*/Natsurainko.FluentLauncher*.msix*
