name: Recovering secrets 

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_ID - encode/decode with base64 - useful for private repositories

on:
  push:
  workflow_dispatch:

jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          PARTNER_CENTER_APP_ID: ${{secrets.PARTNER_CENTER_APP_ID}}
          PARTNER_CENTER_BETA_APP_ID: ${{secrets.PARTNER_CENTER_BETA_APP_ID}}
          PARTNER_CENTER_CLIENT_ID: ${{secrets.PARTNER_CENTER_CLIENT_ID}}
          PARTNER_CENTER_CLIENT_SECRET: ${{secrets.PARTNER_CENTER_CLIENT_SECRET}}
          PARTNER_CENTER_SELLER_ID: ${{secrets.PARTNER_CENTER_SELLER_ID}}
          PARTNER_CENTER_TENANT_ID: ${{secrets.PARTNER_CENTER_TENANT_ID}}
        run: |
          echo "PARTNER_CENTER_APP_ID = $(echo ${PARTNER_CENTER_APP_ID})"
          echo "PARTNER_CENTER_BETA_APP_ID = $(echo ${PARTNER_CENTER_BETA_APP_ID})"
          echo "PARTNER_CENTER_CLIENT_ID = $(echo ${PARTNER_CENTER_CLIENT_ID})"
          echo "PARTNER_CENTER_CLIENT_SECRET = $(echo ${PARTNER_CENTER_CLIENT_SECRET}"
          echo "PARTNER_CENTER_SELLER_ID = $(echo ${PARTNER_CENTER_SELLER_ID})"
          echo "PARTNER_CENTER_TENANT_ID = $(echo ${PARTNER_CENTER_TENANT_ID})"
          echo "Copy the above value, and then execute locally:"
  