name: Run-SyncService
on:
  workflow_call:
    inputs:
      ghp:
        required: false
        type: string
        default: '${{secrets.GIT_HUB_ACCESS_TOKEN}}'
  workflow_dispatch:
    inputs:
        ghp:
          required: false
          type: string
          default: '${{secrets.GIT_HUB_ACCESS_TOKEN}}'
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call-Sync
        run: |
          curl -X POST https://api.github.com/repos/Xcube-Studio/Sync2Oss/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ inputs.ghp }}" \
          --data '{"event_type": "FLPreview"}'
